import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { chapter_library_id, force_regenerate = false } = await req.json();

    if (!chapter_library_id) {
      return new Response(
        JSON.stringify({ error: 'chapter_library_id is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch chapter details
    const { data: chapter, error: fetchError } = await supabase
      .from('chapter_library')
      .select('*')
      .eq('id', chapter_library_id)
      .single();

    if (fetchError) throw fetchError;
    if (!chapter) {
      throw new Error('Chapter not found');
    }

    // Check if full_topics already populated
    if (!force_regenerate && chapter.full_topics && Array.isArray(chapter.full_topics) && chapter.full_topics.length > 0) {
      return new Response(
        JSON.stringify({
          message: 'Full topics already exist (use force_regenerate=true to regenerate)',
          topics: chapter.full_topics
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
    if (!GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    // Generate comprehensive topic list using Gemini
    const systemPrompt = `You are an expert educational content architect for Indian ${chapter.exam_type} preparation.

Generate a COMPREHENSIVE list of 10-15 topics for the chapter "${chapter.chapter_name}" in ${chapter.subject}.

Requirements:
1. Cover ALL major concepts in this chapter
2. Topics should be granular enough for question assignment
3. Use standard terminology from ${chapter.exam_type} syllabus
4. Include both theoretical and application-based topics
5. Order topics from foundational to advanced

For each topic, provide:
- topic_name: Clear, concise topic name
- subtopics: Array of 2-3 key subtopics (optional)
- difficulty: easy/medium/hard
- weightage: Expected exam weightage (1-10)

Return ONLY valid JSON array:
[
  {
    "topic_name": "Introduction and Basic Concepts",
    "subtopics": ["Definition", "Historical Context", "Key Terminology"],
    "difficulty": "easy",
    "weightage": 6
  },
  {
    "topic_name": "Advanced Applications",
    "subtopics": ["Real-world Problems", "Case Studies"],
    "difficulty": "hard",
    "weightage": 9
  }
]

Generate 10-15 comprehensive topics covering the entire chapter.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: systemPrompt }]
          }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 4096,
          }
        })
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API error: ${errorText}`);
    }

    const aiData = await response.json();
    const aiText = aiData.candidates?.[0]?.content?.parts?.[0]?.text || '';
    
    // Clean and parse JSON
    const cleanText = aiText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const topics = JSON.parse(cleanText);

    if (!Array.isArray(topics) || topics.length === 0) {
      throw new Error('Invalid topics generated by AI');
    }

    // Update chapter_library with full_topics
    const { error: updateError } = await supabase
      .from('chapter_library')
      .update({
        full_topics: topics,
        topics_generated: true,
        updated_at: new Date().toISOString()
      })
      .eq('id', chapter_library_id);

    if (updateError) throw updateError;

    return new Response(
      JSON.stringify({
        message: 'Full topics generated successfully',
        chapter_name: chapter.chapter_name,
        topics,
        count: topics.length
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('Error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
