project_id = "qajmtfcphpncqwcrzphm"

[functions.topic-questions-api]
verify_jwt = true

[functions.razorpay-subscription]
verify_jwt = false

[functions.send-payment-invoice]
verify_jwt = false

[functions.ai-extract-all-questions]
verify_jwt = true

[functions.ai-extract-all-questions-chunked]
verify_jwt = true

[functions.save-extracted-questions]
verify_jwt = true

[functions.sync-batch-students]
verify_jwt = true